---
name: Cross-platform tests

# Do this on every push
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install Cargo Make
      uses: davidB/rust-cargo-make@v1

    - name: Install Dependencies
      run: cargo make install_deps

    - name: Run cargo check, fmt, clippy
      run: cargo make ci

    - name: Run tests
      run: cargo test

    - name: Run tests with static feature
      run: cargo test --features static
